### ISSUE TITLE
Add logo to README

### ISSUE THREAD

**Issue by astanush** [fourkitchens/aerate#18]
Add logo to `README.md` for branding purposes.

PNG and SVG versions of logo are here: https://www.dropbox.com/sh/cnetc3u8uxixx6h/AABUJXSpiqgHyuSma5h5W7j6a?dl=0

**Comment by evanmwillhite** [comment]
![aerate-logo](https://user-images.githubusercontent.com/18293479/38391908-572356b2-38eb-11e8-9fd5-62daf5d2bad3.png)

**Comment by evanmwillhite** [comment]
![aerate_results](https://user-images.githubusercontent.com/18293479/38391917-5e7aee02-38eb-11e8-88ad-b863d574f3b8.png)

**Comment by evanmwillhite** [comment]
![aerate-results](https://user-images.githubusercontent.com/18293479/38394090-c088df26-38f2-11e8-8822-efdc361ae00d.jpg)
![aerate-ui](https://user-images.githubusercontent.com/18293479/38394100-c29fb49c-38f2-11e8-91d4-e5e1957ae62c.jpg)

**Comment by evanmwillhite** [comment]
<img width="586" alt="screen shot 2018-04-05 at 5 04 50 pm" src="https://user-images.githubusercontent.com/18293479/38394316-94a27fba-38f3-11e8-96e3-defe9190d536.png">
<img width="1005" alt="screen shot 2018-04-05 at 5 05 12 pm" src="https://user-images.githubusercontent.com/18293479/38394317-959484e0-38f3-11e8-8738-7f63480d6e7c.png">

**Comment by evanmwillhite** [comment]
![screen shot 2018-04-05 at 5 04 50 pm](https://user-images.githubusercontent.com/18293479/38394725-3f7eb0d8-38f5-11e8-80fb-a3a396b55fa7.jpg)
![screen shot 2018-04-05 at 5 05 12 pm](https://user-images.githubusercontent.com/18293479/38394726-3f905ca2-38f5-11e8-9a12-4d1152b083ca.jpg)
